### ISSUE TITLE
Some potential warnings(errors

### ISSUE THREAD

**Issue by felixthoemmes** [dsalfran/ImputeRobust#2]
Hello,
Thanks for contributing this package to CRAN. I have been looking for a way to impute data for variance function regression for quite a while.

I have noticed what I think are potentially bugs in the package. I am using version 1.1-1 and mice 2.30.

When running the example provided (the one in the documentation under the topic mice.impute.gamlss, I am getting the following error:

 In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory

and even though the program finishes and produces an object, there are no imputed values, and all missing values are still NA. 

This error repeats several times when the code runs (12 times for the example above). 

Thanks!

**Comment by dsalfran** [comment]
I'm also running mice 2.30. Running `example(mice.impute.gamlss)` works without problems. What kind system are you running? I think that particular error message is related to R trying to write into a file. The example doesn't write anything.
Thanks for showing interest on the package!

**Comment by felixthoemmes** [comment]
I am on PC - running example(mice.impute.gamlss) also throws 12 warnings. 

Warning messages:
1: In RS() : Algorithm RS has not yet converged
2: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory
3: In RS() : Algorithm RS has not yet converged
4: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory
5: In RS() : Algorithm RS has not yet converged
6: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory
7: In RS() : Algorithm RS has not yet converged
8: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory
9: In RS() : Algorithm RS has not yet converged
10: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory
11: In RS() : Algorithm RS has not yet converged
12: In file(file, if (append) "a" else "w") :
  cannot open file '/dev/null': No such file or directory


This might be related to the system that I am on, but I am not 100% sure.
Again, no imputation actually happened, when I inspect the imputed.sets object. They still contain missing values.

**Comment by felixthoemmes** [comment]
Sys.info() in case it's helpful:


                   sysname                      release                      version                                 machine 
                   "Windows"                      "7 x64" "build 7601, Service Pack 1"                "x86-64"

**Comment by dsalfran** [comment]
I found the error. Some messages from the gamlss function were being redirected to /dev/null with `capture.output`, making the code incompatible with windows. That's fixed now. 
You will still get warnings but they are only related to the quality of the fitted gamlss. It is like this because the fitting algorithm is severely simplified for speed in the example. This can be altered by changing the values of `n.cyc`, `bf.cyc` and `cyc`. For more details read the help files of `gamlss.control` and `glim.control`

**Comment by lorenzwalthert** [comment]
Using continuous integration for the package might be an option to make sure all examples and test run as desired on different operating systems. [App Veyor](https://github.com/krlmlr/r-appveyor) could be used for Windows builds and [travis](https://docs.travis-ci.com/user/languages/r/) which builds on Linux and macOs.

**Comment by felixthoemmes** [comment]
Running now on my PC. Thanks for looking into this.

**Comment by dsalfran** [comment]
I looked into App Veyor and Travis. They will be very useful. Thank you very much.
